### ISSUE TITLE
Add a responsive grid?

### ISSUE THREAD

**Issue by toolness** [GovLab/styleguide#22]
Most developers are used to some kind of responsive grid system (e.g. [bootstrap's](http://getbootstrap.com/css/#grid), [foundation's](http://foundation.zurb.com/sites/docs/grid.html), [pure's](http://purecss.io/grids/)). Will the GovLab style guide have one, or will it be possible to mix-in an existing third-party grid system?

**Comment by claudioccm** [comment]
I created a very simple grid for us. Still need to document it, and make it's page. More soon.
