### ISSUE TITLE
Possibly reduce use of uppercase text-transform

### ISSUE THREAD

**Issue by toolness** [GovLab/styleguide#23]
The aesthetics of the style guide are really great overall, but the one concern I have is the frequent use of `text-transform: uppercase`:

![2015-12-15_6-12-13](https://cloud.githubusercontent.com/assets/124687/11809146/cff0da10-a2f2-11e5-8f8c-4ff9d403cca0.png)

Obviously not all pages are going to look like that, but that particular screenshot does seem rather "shouty".

We should also make sure not to use `text-transform: uppercase` on text fields; here's a concern from an early email exchange on the Network of Innovators form styling:

> For instance, a user could mis-type their name as "JOhn" but not realize that there is a typo until they see the mixed-case version of their name elsewhere on the site.

**Comment by claudioccm** [comment]
I disagree with the "shouty" aspect, since the uppercases are being carefully used in a way to not be too heavy (visually).

Regarding the form, that's already a lesson learned. Hehe. Be sure we won't have that.
