### ISSUE TITLE
Document requirements

### ISSUE THREAD

**Issue by toolness** [GovLab/styleguide#25]
It'd be nice to document the requirements somewhere. Right now, based on the documentation, they seem to be:
- SASS (could be optional for clients that just want to reuse the existing styles and not build on them?)
- Jinja2 (this seems to be required for the search box)
- jQuery (a lot of code examples seem to use it)
- Slick (for the slider)

**Comment by claudioccm** [comment]
sure. Point taken.

**Comment by ghost** [comment]
i believe this is now handled by package.json
