### ISSUE TITLE
Hyperlinks invisible inline

### ISSUE THREAD

**Issue by ghost** [GovLab/styleguide#29]
Should we have an optional class for `a` to allow a different style for hyperlinks that are part of a block of text?

Currently they are indistinguishable from normal text at a glance (example, the 'LINKS AND ANCHORS' section of http://govlab.github.io/styleguide/typography.html)

**Comment by claudioccm** [comment]
yes. 100% agreed. I will create that style.

**Comment by claudioccm** [comment]
this was implemented [here](https://github.com/GovLab/styleguide/commit/b1dd82b4268f3ee6ffe39b91405ed4ef3e9fb9fa)
