### ISSUE TITLE
Would anchors to sub-sections of component pages be a good idea?

### ISSUE THREAD

**Issue by ghost** [GovLab/styleguide#30]

**Comment by claudioccm** [comment]
yes

**Comment by ghost** [comment]
ok i can go thru and update the individual pages

**Comment by claudioccm** [comment]
maybe something like github readme files. The anchor icon that appears on
hover. Let me know

**Comment by ghost** [comment]
that would be cool

**Comment by ghost** [comment]
this is in kss
