### ISSUE TITLE
Proxima Nova isn't an open font

### ISSUE THREAD

**Issue by toolness** [GovLab/styleguide#33]
It actually appears to require a paid TypeKit subscription to access.

This makes it harder for potential open-source volunteers to contribute to the project: just whitelisting "localhost" in our Typekit configuration likely won't be sufficient, as there are plenty of times where we'll want to e.g. test on a mobile device through our home LAN, or show a site to someone via an [ngrok](https://ngrok.com/) tunnel, etc. I've run into these kinds of problems myself already, actually.

I'm also not sure what the legal implications (if any) are of using a closed font in an otherwise 100% open-source project.

Have we considered any open-source alternatives? For example, [Mozilla's Fira Sans](http://mozilla.github.io/Fira/) looks a bit similar... you can compare the two here:
- https://typekit.com/fonts/proxima-nova
- https://typekit.com/fonts/fira-sans

At the very least it'd be nice if we could have our CSS fall-back to a reasonable open default if Proxima Nova isn't available due to licensing issues.

**Comment by toolness** [comment]
Oh, and credit goes to @juliachrusciel for identifying and reporting this issue. Thanks Julia!

**Comment by toolness** [comment]
@chrswng mentioned that we often use [Montserrat](https://www.google.com/fonts/specimen/Montserrat) as an open fallback to Proxima Nova.

**Comment by claudioccm** [comment]
that isn't quite right. Proxima Nova is a professional font, that has
several different weights (Thin, Light, Regular, Semi Bold, Bold, Heavy). I
abuse of that on my design work, and for the govlab projects, I see it as a
very necessary asset. For open source projects, I believe there is a
fallback for a regular "sans-serif" font, which will degrade to
Helvetica/San Francisco on OSX, or Arial for Windows (I think).

RE: Monserrat, it works well as a replacement for Proxima Nova, when we are
using Semi-bold and bold weights. Other than that, it will not work.

**Comment by toolness** [comment]
Sure, that makes sense--just wanted to make sure we explicitly figure this out and document the rationale (if others are coming to contribute to GovLab projects from other open-source projects, they may be confused).

Might also be good for us to build-in the Montserrat fallback into the styleguide's CSS, so that devs and stuff have the best possible fallback in place w/o having to configure extra stuffs.
